# Generated by Django 5.1.4 on 2025-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
