# Generated by Django 5.1.4 on 2025-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
