# Generated by Django 5.1.4 on 2025-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_company_website_experience_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2023-03-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
